apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserver-deployment
  labels:
    app: restserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restserver
  template:
    metadata:
      labels:
        app: restserver
    spec:
      containers:
      - name: restserver
        image: ervmapa/restserver:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: 5001
          initialDelaySeconds: 2
          timeoutSeconds: 2
          periodSeconds: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /alive
            port: 5002
          initialDelaySeconds: 2
          timeoutSeconds: 2
          periodSeconds: 2
          failureThreshold: 2
        ports:
            - containerPort: 5000
            - containerPort: 5001
            - containerPort: 5002

---

apiVersion: v1
kind: Service
metadata:
  name: restserver-service
spec:
  selector:
    app: restserver
  ports:
    - name: port-5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31000
      port: 5000
    - name: port-5001
      protocol: TCP
      targetPort: 5001
      nodePort: 31001
      port: 5001
    - name: port-5002
      protocol: TCP
      targetPort: 5002
      nodePort: 31002
      port: 5002
  type: NodePort

